---
Description: "AWS Glue Job Test"
Resources:
  MyJobRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/PowerUserAccess
        
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
 
  MyJob:
    Type: AWS::Glue::Job
    Properties:
      MaxRetries: 0
      GlueVersion: 2.0
      NumberOfWorkers: 2
      Timeout: 10
      ExecutionProperty:
         MaxConcurrentRuns: 1
      WorkerType: "Standard"
      Command:
        Name: glueetl
        ScriptLocation: "s3://tweets-meta-data/scripts/get_entity_table_withBookmark.py"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        '--TempDir': "s3://tweets-meta-data/GlueJobTemp/"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: GlueJobGetTweetsEntities
      Role: !Ref MyJobRole